#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

if [[ -f "$SCRIPT_DIR/.env" ]]; then
  echo "Loading configuration from infra/.env"
  set -a; source "$SCRIPT_DIR/.env"; set +a
fi

RG_NAME="${RG_NAME:-millets-momo-rg}"
LOCATION="${LOCATION:-centralindia}"
BASE_NAME="${BASE_NAME:-millets-momo}"
SQL_ADMIN_USER="${SQL_ADMIN_USER:-momoadmin}"
SQL_ADMIN_PASSWORD="${SQL_ADMIN_PASSWORD:-}"
SQL_DB_NAME="${SQL_DB_NAME:-${BASE_NAME}-db}"
CLIENT_IP="${CLIENT_IP:-}"

DEPLOYMENT_NAME="${BASE_NAME}-sql-$(date +%Y%m%d%H%M%S)"

if [[ -z "$SQL_ADMIN_PASSWORD" ]]; then
  echo "SQL_ADMIN_PASSWORD not set. Auto-generating..."
  SQL_ADMIN_PASSWORD=$(openssl rand -base64 20 | tr -d '/+=')
  echo "Generated SQL_ADMIN_PASSWORD: $SQL_ADMIN_PASSWORD"
fi

if [[ -z "$CLIENT_IP" ]]; then
  echo "Auto-detecting client IP..."
  CLIENT_IP=$(curl -s https://checkip.amazonaws.com 2>/dev/null || echo "")
  if [[ -z "$CLIENT_IP" ]]; then
    echo "Warning: Could not detect client IP. SQL firewall rule will not be created." >&2
  else
    echo "Detected client IP: $CLIENT_IP"
  fi
fi

ENV_FILE="$SCRIPT_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<EOF
# auto-generated by deploy-sql.sh — do not commit
RG_NAME=$RG_NAME
LOCATION=$LOCATION
BASE_NAME=$BASE_NAME
SQL_ADMIN_USER=$SQL_ADMIN_USER
SQL_ADMIN_PASSWORD=$SQL_ADMIN_PASSWORD
SQL_DB_NAME=$SQL_DB_NAME
CLIENT_IP=$CLIENT_IP
EOF
  echo "Saved configuration to $ENV_FILE"
else
  # Update .env with latest values
  sed -i.bak "s|^SQL_ADMIN_PASSWORD=.*|SQL_ADMIN_PASSWORD=$SQL_ADMIN_PASSWORD|" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
  sed -i.bak "s|^CLIENT_IP=.*|CLIENT_IP=$CLIENT_IP|" "$ENV_FILE" && rm -f "$ENV_FILE.bak"
fi

echo ""
echo "=== SQL Deployment Configuration ==="
echo "  Resource Group : $RG_NAME"
echo "  Location       : $LOCATION"
echo "  SQL Server      : ${BASE_NAME}-sql"
echo "  SQL Database    : $SQL_DB_NAME"
echo "  SQL Admin User  : $SQL_ADMIN_USER"
echo "  Client IP       : ${CLIENT_IP:-none}"
echo ""

echo "Creating resource group: $RG_NAME in $LOCATION"
az group create --name "$RG_NAME" --location "$LOCATION" --tags project="$BASE_NAME" 2>/dev/null || true

echo "Deploying SQL resources..."
DEPLOY_OUTPUT=$(az deployment group create \
  --resource-group "$RG_NAME" \
  --name "$DEPLOYMENT_NAME" \
  --template-file "$PROJECT_ROOT/infra/sql.bicep" \
  --parameters \
      baseName="$BASE_NAME" \
      location="$LOCATION" \
      sqlAdminUser="$SQL_ADMIN_USER" \
      sqlAdminPassword="$SQL_ADMIN_PASSWORD" \
      sqlDbName="$SQL_DB_NAME" \
      clientIp="$CLIENT_IP" \
  --query 'properties.outputs' \
  --output json)

echo ""
echo "=== Deployment Outputs ==="
echo "$DEPLOY_OUTPUT" | jq '.'

SQL_FQDN=$(echo "$DEPLOY_OUTPUT" | jq -r '.sqlServerFqdn.value // empty')
SQL_DB_NAME_OUT=$(echo "$DEPLOY_OUTPUT" | jq -r '.sqlDatabaseName.value // empty')

if [[ -n "$SQL_FQDN" ]]; then
  echo ""
  echo "SQL Server: $SQL_FQDN"
  echo "SQL Database: $SQL_DB_NAME_OUT"
  echo "SQL Admin User: $SQL_ADMIN_USER"
fi

LOCAL_SETTINGS="$PROJECT_ROOT/apps/backend/local.settings.json"
if [[ -f "$LOCAL_SETTINGS" ]] && [[ -n "$SQL_FQDN" ]]; then
  echo ""
  echo "Updating $LOCAL_SETTINGS with SQL connection details..."
  TMP_SETTINGS=$(mktemp)
  jq --arg server "$SQL_FQDN" \
     --arg db "$SQL_DB_NAME_OUT" \
     --arg user "$SQL_ADMIN_USER" \
     --arg pass "$SQL_ADMIN_PASSWORD" \
     '.Values.SQL_SERVER = $server | .Values.SQL_DATABASE = $db | .Values.SQL_USER = $user | .Values.SQL_PASSWORD = $pass | .Values.SQL_PORT = "1433" | .Values.SQL_ENCRYPT = "true" | .Values.SQL_TRUST_CERT = "false"' \
     "$LOCAL_SETTINGS" > "$TMP_SETTINGS" && mv "$TMP_SETTINGS" "$LOCAL_SETTINGS"
  echo "Done. local.settings.json updated."
fi

echo ""
echo "=== Next step ==="
echo "Run database migration:"
echo "  npm run db:migrate"