#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Source .env file if it exists (copy .env.example → .env, fill in values)
if [[ -f "$SCRIPT_DIR/.env" ]]; then
  echo "Loading configuration from infra/.env"
  set -a; source "$SCRIPT_DIR/.env"; set +a
fi

# --- Configuration (all overridable via env vars or .env) ---
RG_NAME="${RG_NAME:-millets-momo-rg}"
LOCATION="${LOCATION:-centralindia}"
BASE_NAME="${BASE_NAME:-millets-momo}"
DATABASE_URL="${DATABASE_URL:-}"
MM_TOKEN_SECRET="${MM_TOKEN_SECRET:-}"
ALLOWED_ORIGINS="${ALLOWED_ORIGINS:-}"
REPO_URL="${REPO_URL:-}"
REPOSITORY_TOKEN="${REPOSITORY_TOKEN:-}"
BRANCH="${BRANCH:-main}"

DEPLOYMENT_NAME="${BASE_NAME}-$(date +%Y%m%d%H%M%S)"

# The database lives on Supabase, so there is nothing to provision for it and
# no admin password to generate — only a connection string to pass through.
if [[ -z "$DATABASE_URL" ]]; then
  echo "DATABASE_URL is not set." >&2
  echo "Copy it from Supabase → Connect → Transaction pooler (shared, port 6543)" >&2
  echo "and put it in infra/.env as DATABASE_URL=postgresql://..." >&2
  exit 1
fi

if [[ -z "$MM_TOKEN_SECRET" ]]; then
  echo "MM_TOKEN_SECRET not set. Auto-generating a stronger production secret..."
  MM_TOKEN_SECRET=$(openssl rand -base64 32 | tr -d '/+=')
  echo "Generated MM_TOKEN_SECRET (save this!): $MM_TOKEN_SECRET"
fi

if [[ -z "$REPOSITORY_TOKEN" ]]; then
  echo "Warning: REPOSITORY_TOKEN not set. SWA GitHub CI/CD will not work." >&2
  echo "Set it to a GitHub PAT with repo access if you want auto-deploys." >&2
fi

# --- Persist generated values to .env for future runs ---
ENV_FILE="$SCRIPT_DIR/.env"
if [[ ! -f "$ENV_FILE" ]]; then
  cat > "$ENV_FILE" <<EOF
# auto-generated by deploy.sh — do not commit this file
RG_NAME=$RG_NAME
LOCATION=$LOCATION
BASE_NAME=$BASE_NAME
DATABASE_URL=$DATABASE_URL
MM_TOKEN_SECRET=$MM_TOKEN_SECRET
ALLOWED_ORIGINS=$ALLOWED_ORIGINS
REPO_URL=$REPO_URL
REPOSITORY_TOKEN=$REPOSITORY_TOKEN
BRANCH=$BRANCH
EOF
  echo "Saved configuration to $ENV_FILE"
  echo "IMPORTANT: Add infra/.env to .gitignore! (It contains secrets.)"
fi

echo ""
echo "=== Deployment Configuration ==="
echo "  Resource Group : $RG_NAME"
echo "  Location       : $LOCATION"
echo "  Base Name      : $BASE_NAME"
echo "  SWA App        : ${BASE_NAME}-swa"
echo "  Database       : Supabase (not provisioned by this script)"
echo ""

# --- Create resource group ---
echo "Creating resource group: $RG_NAME in $LOCATION"
az group create --name "$RG_NAME" --location "$LOCATION" --tags project="$BASE_NAME"

# --- Deploy Bicep template ---
echo "Deploying Bicep template..."
DEPLOY_OUTPUT=$(az deployment group create \
  --resource-group "$RG_NAME" \
  --name "$DEPLOYMENT_NAME" \
  --template-file "$PROJECT_ROOT/infra/main.bicep" \
  --parameters \
      baseName="$BASE_NAME" \
      location="$LOCATION" \
      databaseUrl="$DATABASE_URL" \
      tokenSecret="$MM_TOKEN_SECRET" \
      allowedOrigins="$ALLOWED_ORIGINS" \
      repoUrl="$REPO_URL" \
      repositoryToken="$REPOSITORY_TOKEN" \
      branch="$BRANCH" \
  --query 'properties.outputs' \
  --output json)

echo ""
echo "=== Deployment Outputs ==="
echo "$DEPLOY_OUTPUT" | jq '.'

SWA_URL=$(echo "$DEPLOY_OUTPUT" | jq -r '.swaDefaultUrl.value // empty')

if [[ -n "$SWA_URL" ]]; then
  echo ""
  echo "SWA URL: $SWA_URL"
fi

echo ""
echo "=== Next steps ==="
echo "1. Run database migration (first time only):"
echo "   npm run prod:db:migrate"
echo ""
echo "2. Get SWA deployment token for GitHub Actions:"
echo "   az staticwebapp secrets list --name ${BASE_NAME}-swa --resource-group $RG_NAME --query properties.apiKey -o tsv"
echo ""
echo "3. Add GitHub repo secrets (Settings → Secrets → Actions):"
echo "   AZURE_STATIC_WEB_APPS_API_TOKEN  — from step 2"
echo "   DATABASE_URL, MM_TOKEN_SECRET"
echo ""
echo "4. If using GitHub Actions CI/CD, set REPO_URL in infra/.env (owner/repo format)"
