-- Postgres schema for Supabase. Converted from the previous Azure SQL schema.
--
-- Differences from the T-SQL original, all deliberate:
--   * Identifiers are snake_case. Postgres folds unquoted names to lowercase,
--     so the old PascalCase table names would have needed quoting everywhere.
--   * NVARCHAR(n) -> VARCHAR(n), NVARCHAR(MAX) -> TEXT. Postgres text is always
--     Unicode, so the N-prefix distinction does not exist.
--   * BIT -> BOOLEAN. Drivers then hand the app real booleans instead of 0/1.
--   * DATETIME2 + SYSUTCDATETIME() -> TIMESTAMPTZ + NOW(). Storing the zone
--     removes the unwritten "these are UTC" rule the old columns relied on.
--   * IDENTITY is GENERATED BY DEFAULT, not ALWAYS: the data migration and the
--     beverage rows both insert explicit ids. Sequences are realigned at the
--     end of seed.sql.

DROP TABLE IF EXISTS cylinder_refills           CASCADE;
DROP TABLE IF EXISTS day_expenses               CASCADE;
DROP TABLE IF EXISTS client_activity_logs       CASCADE;
DROP TABLE IF EXISTS staff_operation_logs       CASCADE;
DROP TABLE IF EXISTS daily_closing_stock        CASCADE;
DROP TABLE IF EXISTS supply_verifications       CASCADE;
DROP TABLE IF EXISTS supply_order_logs          CASCADE;
DROP TABLE IF EXISTS daily_supply_order_items   CASCADE;
DROP TABLE IF EXISTS daily_supply_orders        CASCADE;
DROP TABLE IF EXISTS supply_items               CASCADE;
DROP TABLE IF EXISTS order_items                CASCADE;
DROP TABLE IF EXISTS orders                     CASCADE;
DROP TABLE IF EXISTS menu_items                 CASCADE;
DROP TABLE IF EXISTS daily_payment_settlements  CASCADE;
DROP TABLE IF EXISTS users                      CASCADE;

CREATE TABLE users (
  id           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username     VARCHAR(50)  NOT NULL UNIQUE,
  role         VARCHAR(20)  NOT NULL CHECK (role IN ('staff','admin')),
  pin_hash     VARCHAR(255) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  created_at   TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE TABLE menu_items (
  id           INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  filling      VARCHAR(30)  NOT NULL,
  preparation  VARCHAR(30)  NOT NULL,
  display_name VARCHAR(60)  NOT NULL,
  full_price   NUMERIC(6,2) NOT NULL,
  half_price   NUMERIC(6,2) NOT NULL,
  is_active    BOOLEAN      NOT NULL DEFAULT TRUE,
  CONSTRAINT uq_menu_items_combo UNIQUE (filling, preparation)
);

-- id is assigned by the app, not the database, so there is no identity here.
CREATE TABLE orders (
  id              BIGINT       NOT NULL PRIMARY KEY,
  order_date      DATE         NOT NULL,
  time_label      VARCHAR(20)  NOT NULL,
  order_type      VARCHAR(10)  NOT NULL CHECK (order_type IN ('dine','pack')),
  payment_method  VARCHAR(10)  NOT NULL CHECK (payment_method IN ('cash','upi','split','pending')),
  is_completed    BOOLEAN      NOT NULL DEFAULT FALSE,
  total_amount    NUMERIC(8,2) NOT NULL,
  cash_amount     NUMERIC(8,2) NOT NULL DEFAULT 0,
  upi_amount      NUMERIC(8,2) NOT NULL DEFAULT 0,
  created_by      INTEGER      NULL REFERENCES users(id),
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  completed_at    TIMESTAMPTZ  NULL,
  comment         VARCHAR(500) NULL
);

CREATE INDEX ix_orders_order_date ON orders(order_date);
CREATE INDEX ix_orders_completed  ON orders(order_date, is_completed);

CREATE TABLE order_items (
  id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id      BIGINT       NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  menu_item_id  INTEGER      NOT NULL REFERENCES menu_items(id),
  item_name     VARCHAR(60)  NOT NULL,
  quantity      INTEGER      NOT NULL CHECK (quantity > 0),
  is_half       BOOLEAN      NOT NULL DEFAULT FALSE,
  unit_price    NUMERIC(6,2) NOT NULL,
  line_total    NUMERIC(8,2) NOT NULL
);

CREATE INDEX ix_order_items_order_id ON order_items(order_id);

CREATE TABLE supply_items (
  id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          VARCHAR(60)  NOT NULL UNIQUE,
  category      VARCHAR(20)  NOT NULL CHECK (category IN ('momo_packet','sauce','dip')),
  unit_price    NUMERIC(8,2) NOT NULL,
  pieces_per    INTEGER      NOT NULL DEFAULT 1,
  display_name  VARCHAR(80)  NOT NULL,
  is_active     BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE daily_supply_orders (
  id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date    DATE          NOT NULL,
  total_cost    NUMERIC(10,2) NOT NULL,
  created_by    INTEGER       NOT NULL REFERENCES users(id),
  created_at    TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_daily_supply_orders_date UNIQUE (order_date)
);

CREATE TABLE daily_supply_order_items (
  id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id        INTEGER       NOT NULL REFERENCES daily_supply_orders(id) ON DELETE CASCADE,
  supply_item_id  INTEGER       NOT NULL REFERENCES supply_items(id),
  quantity        INTEGER       NOT NULL CHECK (quantity > 0),
  unit_price      NUMERIC(8,2)  NOT NULL,
  line_total      NUMERIC(10,2) NOT NULL
);

CREATE INDEX ix_daily_supply_order_items_order_id ON daily_supply_order_items(order_id);

CREATE TABLE supply_order_logs (
  id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date    DATE         NOT NULL,
  action        VARCHAR(10)  NOT NULL CHECK (action IN ('CREATE','UPDATE')),
  created_by    INTEGER      NOT NULL REFERENCES users(id),
  created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  item_summary  VARCHAR(500) NOT NULL
);

CREATE INDEX ix_supply_order_logs_date       ON supply_order_logs(order_date DESC);
CREATE INDEX ix_supply_order_logs_created_at ON supply_order_logs(created_at DESC);

CREATE TABLE supply_verifications (
  id              INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date      DATE        NOT NULL,
  supply_item_id  INTEGER     NOT NULL REFERENCES supply_items(id),
  expected_qty    INTEGER     NOT NULL,
  actual_qty      INTEGER     NOT NULL,
  has_conflict    BOOLEAN     NOT NULL DEFAULT FALSE,
  reported_by     INTEGER     NOT NULL REFERENCES users(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_supply_verification_date_item UNIQUE (order_date, supply_item_id)
);

CREATE INDEX ix_supply_verifications_date ON supply_verifications(order_date DESC);

CREATE TABLE daily_closing_stock (
  id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date      DATE         NOT NULL,
  supply_item_id  INTEGER      NOT NULL REFERENCES supply_items(id),
  packets_left    INTEGER      NOT NULL DEFAULT 0,
  pieces_left     INTEGER      NOT NULL DEFAULT 0 CHECK (pieces_left >= 0 AND pieces_left < 24),
  wastage_pieces  INTEGER      NOT NULL DEFAULT 0,
  has_conflict    BOOLEAN      NOT NULL DEFAULT FALSE,
  conflict_reason VARCHAR(500) NULL,
  reported_by     INTEGER      NOT NULL REFERENCES users(id),
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_daily_closing_stock_date_item UNIQUE (order_date, supply_item_id)
);

CREATE INDEX ix_daily_closing_stock_date ON daily_closing_stock(order_date DESC);

CREATE TABLE staff_operation_logs (
  id              INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date      DATE         NOT NULL,
  operation_type  VARCHAR(20)  NOT NULL,
  created_by      INTEGER      NOT NULL REFERENCES users(id),
  created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
  details         VARCHAR(500) NOT NULL,
  metadata        TEXT         NULL,
  CONSTRAINT ck_staff_operation_logs_type CHECK (operation_type IN (
    'verification','closing_stock','order_create','order_update',
    'order_complete','order_delete','supply_order','payment_settlement',
    'expense_save','cylinder_refill','login'
  ))
);

CREATE INDEX ix_staff_operation_logs_date       ON staff_operation_logs(order_date DESC);
CREATE INDEX ix_staff_operation_logs_created_at ON staff_operation_logs(created_at DESC);
CREATE INDEX ix_staff_operation_logs_type       ON staff_operation_logs(operation_type);

-- created_at defaulted to GETDATE() (server local time) under Azure SQL while
-- every other table used UTC. NOW() makes this column agree with the rest.
CREATE TABLE client_activity_logs (
  id            INTEGER      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       INTEGER      NULL,
  user_role     VARCHAR(20)  NULL,
  log_type      VARCHAR(50)  NOT NULL,
  page          VARCHAR(100) NULL,
  details       VARCHAR(500) NULL,
  metadata      TEXT         NULL,
  device_info   VARCHAR(500) NULL,
  duration_ms   INTEGER      NULL,
  created_at    TIMESTAMPTZ  DEFAULT NOW()
);

CREATE INDEX ix_client_activity_logs_type       ON client_activity_logs(log_type);
CREATE INDEX ix_client_activity_logs_created_at ON client_activity_logs(created_at DESC);

CREATE TABLE daily_payment_settlements (
  id              INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date      DATE          NOT NULL,
  expected_cash   NUMERIC(10,2) NOT NULL DEFAULT 0,
  expected_upi    NUMERIC(10,2) NOT NULL DEFAULT 0,
  actual_cash     NUMERIC(10,2) NOT NULL DEFAULT 0,
  actual_upi      NUMERIC(10,2) NOT NULL DEFAULT 0,
  cash_conflict   BOOLEAN       NOT NULL DEFAULT FALSE,
  upi_conflict    BOOLEAN       NOT NULL DEFAULT FALSE,
  notes           VARCHAR(500)  NULL,
  created_by      INTEGER       NOT NULL REFERENCES users(id),
  created_at      TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_daily_payment_settlement_date UNIQUE (order_date)
);

CREATE INDEX ix_daily_payment_settlements_date ON daily_payment_settlements(order_date DESC);

CREATE TABLE day_expenses (
  id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_date   DATE          NOT NULL,
  description  VARCHAR(200)  NOT NULL,
  amount       NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  created_by   INTEGER       NOT NULL REFERENCES users(id),
  created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE INDEX ix_day_expenses_date ON day_expenses(order_date DESC);

-- Gas cylinder refills. Kept apart from day_expenses because the weekly
-- cleanup clears those, and admin needs refill history month by month.
CREATE TABLE cylinder_refills (
  id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  refill_date  DATE          NOT NULL,
  brand        VARCHAR(10)   NOT NULL CHECK (brand IN ('HP','BP','INDANE')),
  amount       NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  source       VARCHAR(100)  NULL,
  created_by   INTEGER       NOT NULL REFERENCES users(id),
  created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_by   INTEGER       NULL REFERENCES users(id),
  updated_at   TIMESTAMPTZ   NULL
);

CREATE INDEX ix_cylinder_refills_date ON cylinder_refills(refill_date DESC);
