-- Postgres seed. Converted from the previous Azure SQL seed.
--
-- T-SQL MERGE becomes INSERT ... ON CONFLICT, which keys off the unique
-- constraints already declared in schema.sql rather than an ON clause.
-- Re-running this file is safe and realigns prices with the code.

-- ============================================
-- 1. Menu items (28 momo rows)
-- ============================================
-- Order matters: these take ids 1-28 and must line up with buildMenu() in
-- src/constants/menu.ts, because order_items.menu_item_id is a foreign key.
INSERT INTO menu_items (filling, preparation, display_name, full_price, half_price)
VALUES
  ('Veg', 'Steam', 'Veg Steam', 89.00, 50.00),
  ('Paneer', 'Steam', 'Paneer Steam', 109.00, 60.00),
  ('Cheese Corn', 'Steam', 'Cheese Corn Steam', 129.00, 70.00),
  ('Platter', 'Steam', 'Platter Steam', 109.00, 60.00),
  ('Veg', 'Fry', 'Veg Fry', 109.00, 60.00),
  ('Paneer', 'Fry', 'Paneer Fry', 129.00, 70.00),
  ('Cheese Corn', 'Fry', 'Cheese Corn Fry', 149.00, 80.00),
  ('Platter', 'Fry', 'Platter Fry', 129.00, 70.00),
  ('Veg', 'Creamy', 'Veg Creamy', 129.00, 60.00),
  ('Paneer', 'Creamy', 'Paneer Creamy', 129.00, 70.00),
  ('Cheese Corn', 'Creamy', 'Cheese Corn Creamy', 149.00, 80.00),
  ('Platter', 'Creamy', 'Platter Creamy', 129.00, 70.00),
  ('Veg', 'Creamy Fry', 'Veg Creamy Fry', 129.00, 70.00),
  ('Paneer', 'Creamy Fry', 'Paneer Creamy Fry', 149.00, 80.00),
  ('Cheese Corn', 'Creamy Fry', 'Cheese Corn Creamy Fry', 169.00, 90.00),
  ('Platter', 'Creamy Fry', 'Platter Creamy Fry', 149.00, 80.00),
  ('Veg', 'Nepalese Kothey', 'Veg Nepalese Kothey', 129.00, 70.00),
  ('Paneer', 'Nepalese Kothey', 'Paneer Nepalese Kothey', 139.00, 75.00),
  ('Cheese Corn', 'Nepalese Kothey', 'Cheese Corn Nepalese Kothey', 149.00, 80.00),
  ('Platter', 'Nepalese Kothey', 'Platter Nepalese Kothey', 139.00, 75.00),
  ('Veg', 'Pan Fried Gravy', 'Veg Pan Fried Gravy', 139.00, 75.00),
  ('Paneer', 'Pan Fried Gravy', 'Paneer Pan Fried Gravy', 149.00, 80.00),
  ('Cheese Corn', 'Pan Fried Gravy', 'Cheese Corn Pan Fried Gravy', 159.00, 85.00),
  ('Platter', 'Pan Fried Gravy', 'Platter Pan Fried Gravy', 149.00, 80.00),
  ('Veg', 'Fried Peri Peri', 'Veg Fried Peri Peri', 129.00, 70.00),
  ('Paneer', 'Fried Peri Peri', 'Paneer Fried Peri Peri', 149.00, 80.00),
  ('Cheese Corn', 'Fried Peri Peri', 'Cheese Corn Fried Peri Peri', 169.00, 90.00),
  ('Platter', 'Fried Peri Peri', 'Platter Fried Peri Peri', 149.00, 80.00)
ON CONFLICT (filling, preparation) DO NOTHING;

-- Beverages (flat unit price, no half plate). Ids are explicit and must match
-- buildMenu(): momos hold 1-28, beverages 29-30. Postgres allows the explicit
-- id because the identity column is GENERATED BY DEFAULT, not ALWAYS.
INSERT INTO menu_items (id, filling, preparation, display_name, full_price, half_price)
VALUES
  (29, 'Cold Drink', 'Beverages', 'Cold Drink', 10.00, 10.00),
  (30, 'Water', 'Beverages', 'Water', 10.00, 10.00)
ON CONFLICT (id) DO UPDATE
  SET preparation = EXCLUDED.preparation,
      display_name = EXCLUDED.display_name,
      full_price = EXCLUDED.full_price,
      half_price = EXCLUDED.half_price,
      is_active = TRUE;

-- ============================================
-- 2. User accounts
-- ============================================
-- PINs for login (4-digit):
--   Admin    -> 1703
--   Staff    -> 9865
--   Staff 2  -> 5575
--
-- Generate new hashes: npm run generate-pin-hash <pin>
--
INSERT INTO users (username, role, pin_hash, display_name)
VALUES
  ('staff', 'staff', '$2b$10$veSawKHMM2U3EV08JXrs/uFmhfLxsHqLvOij6JjB2.1NG6iGsttA2', 'Cart Staff'),
  ('staff_2', 'staff', '$2b$10$/rFwh8e6p7wL.awaXNLdnuelALpgODMcHsBUlBDvyiyH/H0ggeSRS', 'Staff 2'),
  ('admin', 'admin', '$2b$10$nQTAqER/jcLsoC0nYyl2OeOXt7fZ0tqXRhwSl3MBxRGIgVLnkjtrO', 'Owner')
ON CONFLICT (username) DO UPDATE
  SET pin_hash = EXCLUDED.pin_hash,
      role = EXCLUDED.role,
      display_name = EXCLUDED.display_name;

-- ============================================
-- 3. Supply items (8 items: 3 momo packets + 5 sauces/dips)
-- ============================================
INSERT INTO supply_items (name, category, unit_price, pieces_per, display_name)
VALUES
  ('veg_packet', 'momo_packet', 138.00, 24, 'Veg Momo Packet (24 Pcs)'),
  ('paneer_packet', 'momo_packet', 158.00, 24, 'Paneer Momo Packet (24 Pcs)'),
  ('cheese_corn_packet', 'momo_packet', 198.00, 24, 'CheeseCorn Momo Packet (24 Pcs)'),
  ('red_sauce', 'sauce', 80.00, 1, 'Red Sauce'),
  ('chipotle', 'dip', 220.00, 1, 'Chipotle'),
  ('schezwan_sauce', 'sauce', 170.00, 1, 'Schezwan Sauce'),
  ('oregano', 'dip', 370.00, 1, 'Oregano'),
  ('molten_cheese', 'dip', 160.00, 1, 'Molten Cheese')
ON CONFLICT (name) DO UPDATE
  SET category = EXCLUDED.category,
      unit_price = EXCLUDED.unit_price,
      pieces_per = EXCLUDED.pieces_per,
      display_name = EXCLUDED.display_name;

-- Rows inserted with an explicit id leave the identity sequence behind, so the
-- next generated id would collide. Realign every sequence with its table.
SELECT setval(pg_get_serial_sequence('menu_items', 'id'), COALESCE((SELECT MAX(id) FROM menu_items), 1));
SELECT setval(pg_get_serial_sequence('users', 'id'), COALESCE((SELECT MAX(id) FROM users), 1));
SELECT setval(pg_get_serial_sequence('supply_items', 'id'), COALESCE((SELECT MAX(id) FROM supply_items), 1));
