-- Adds staff leaves and staff takeaways to an existing database without
-- touching its data. schema.sql drops every table, so it cannot be used on
-- production; run this instead:
--   npm run prod:db:apply -- 2026-09-25-staff-leaves-takeaways.sql
-- Safe to run more than once, and independent of the cylinder migration.

BEGIN;

CREATE TABLE IF NOT EXISTS staff_leaves (
  id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_name   VARCHAR(60)   NOT NULL,
  leave_date   DATE          NOT NULL,
  reason       VARCHAR(200)  NULL,
  created_by   INTEGER       NOT NULL REFERENCES users(id),
  created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_by   INTEGER       NULL REFERENCES users(id),
  updated_at   TIMESTAMPTZ   NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_staff_leaves_name_date ON staff_leaves(lower(staff_name), leave_date);
CREATE INDEX IF NOT EXISTS ix_staff_leaves_date ON staff_leaves(leave_date DESC);

CREATE TABLE IF NOT EXISTS staff_takeaways (
  id             INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_name     VARCHAR(60)   NOT NULL,
  takeaway_date  DATE          NOT NULL,
  note           VARCHAR(200)  NULL,
  menu_value     NUMERIC(8,2)  NOT NULL,
  discount_pct   NUMERIC(5,2)  NOT NULL,
  amount_owed    NUMERIC(8,2)  NOT NULL,
  created_by     INTEGER       NOT NULL REFERENCES users(id),
  created_at     TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_by     INTEGER       NULL REFERENCES users(id),
  updated_at     TIMESTAMPTZ   NULL
);

CREATE INDEX IF NOT EXISTS ix_staff_takeaways_date ON staff_takeaways(takeaway_date DESC);

CREATE TABLE IF NOT EXISTS staff_takeaway_items (
  id            INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  takeaway_id   INTEGER       NOT NULL REFERENCES staff_takeaways(id) ON DELETE CASCADE,
  menu_item_id  INTEGER       NOT NULL REFERENCES menu_items(id),
  item_name     VARCHAR(60)   NOT NULL,
  quantity      INTEGER       NOT NULL CHECK (quantity > 0),
  is_half       BOOLEAN       NOT NULL DEFAULT FALSE,
  menu_price    NUMERIC(8,2)  NOT NULL,
  line_total    NUMERIC(8,2)  NOT NULL
);

CREATE INDEX IF NOT EXISTS ix_staff_takeaway_items_takeaway ON staff_takeaway_items(takeaway_id);

-- Allow staff_leave and staff_takeaway in the staff log.
-- Rewritten only while 'staff_takeaway' is missing, so re-running this after a later
-- migration cannot drop the log types that one added.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_staff_operation_logs_type'
      AND pg_get_constraintdef(oid) LIKE '%''staff_takeaway''%'
  ) THEN
    ALTER TABLE staff_operation_logs DROP CONSTRAINT IF EXISTS ck_staff_operation_logs_type;
    ALTER TABLE staff_operation_logs ADD CONSTRAINT ck_staff_operation_logs_type CHECK (operation_type IN (
  'verification','closing_stock','order_create','order_update',
  'order_complete','order_delete','supply_order','payment_settlement',
  'expense_save','cylinder_refill','staff_leave','staff_takeaway','login'
));
  END IF;
END $$;

COMMIT;
