-- Adds gas cylinder refill tracking to an existing database without touching
-- its data. schema.sql drops every table, so it cannot be used on production;
-- run this instead: npm run prod:db:apply -- 2026-09-24-cylinder-refills.sql
-- Safe to run more than once.

BEGIN;

CREATE TABLE IF NOT EXISTS cylinder_refills (
  id           INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  refill_date  DATE          NOT NULL,
  brand        VARCHAR(10)   NOT NULL CHECK (brand IN ('HP','BP','INDANE')),
  amount       NUMERIC(10,2) NOT NULL CHECK (amount > 0),
  source       VARCHAR(100)  NULL,
  created_by   INTEGER       NOT NULL REFERENCES users(id),
  created_at   TIMESTAMPTZ   NOT NULL DEFAULT NOW(),
  updated_by   INTEGER       NULL REFERENCES users(id),
  updated_at   TIMESTAMPTZ   NULL
);

-- Columns added after the table first shipped; a no-op on a fresh create.
ALTER TABLE cylinder_refills ADD COLUMN IF NOT EXISTS source     VARCHAR(100) NULL;
ALTER TABLE cylinder_refills ADD COLUMN IF NOT EXISTS updated_by INTEGER      NULL REFERENCES users(id);
ALTER TABLE cylinder_refills ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ  NULL;

CREATE INDEX IF NOT EXISTS ix_cylinder_refills_date ON cylinder_refills(refill_date DESC);

-- Allow cylinder_refill in the staff log.
-- Rewritten only while 'cylinder_refill' is missing, so re-running this after a later
-- migration cannot drop the log types that one added.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_staff_operation_logs_type'
      AND pg_get_constraintdef(oid) LIKE '%''cylinder_refill''%'
  ) THEN
    ALTER TABLE staff_operation_logs DROP CONSTRAINT IF EXISTS ck_staff_operation_logs_type;
    ALTER TABLE staff_operation_logs ADD CONSTRAINT ck_staff_operation_logs_type CHECK (operation_type IN (
  'verification','closing_stock','order_create','order_update',
  'order_complete','order_delete','supply_order','payment_settlement',
  'expense_save','cylinder_refill','login'
));
  END IF;
END $$;

COMMIT;
