-- Adds closing cash and admin push subscriptions to an existing database
-- without touching its data. Run on production with:
--   npm run prod:db:apply -- 2026-10-09-closing-cash-push.sql
-- Safe to run more than once.

BEGIN;

CREATE TABLE IF NOT EXISTS daily_closing_cash (
  order_date   DATE          PRIMARY KEY,
  amount       NUMERIC(10,2) NOT NULL CHECK (amount >= 0),
  recorded_by  INTEGER       NOT NULL REFERENCES users(id),
  recorded_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id          INTEGER       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endpoint    TEXT          NOT NULL UNIQUE,
  p256dh      VARCHAR(200)  NOT NULL,
  auth        VARCHAR(100)  NOT NULL,
  user_id     INTEGER       NOT NULL REFERENCES users(id),
  created_at  TIMESTAMPTZ   NOT NULL DEFAULT NOW()
);

-- Allow closing_cash in the staff log.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'ck_staff_operation_logs_type'
      AND pg_get_constraintdef(oid) LIKE '%''closing_cash''%'
  ) THEN
    ALTER TABLE staff_operation_logs DROP CONSTRAINT IF EXISTS ck_staff_operation_logs_type;
    ALTER TABLE staff_operation_logs ADD CONSTRAINT ck_staff_operation_logs_type CHECK (operation_type IN (
  'verification','closing_stock','order_create','order_update',
  'order_complete','order_delete','supply_order','payment_settlement',
  'expense_save','cylinder_refill','staff_leave','staff_takeaway','closing_cash','login'
));
  END IF;
END $$;

COMMIT;
